// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fitModel_cpp
Rcpp::List fitModel_cpp(Rcpp::List args_data, Rcpp::List args_model);
RcppExport SEXP _PALM_fitModel_cpp(SEXP args_dataSEXP, SEXP args_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args_data(args_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_model(args_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(fitModel_cpp(args_data, args_model));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PALM_fitModel_cpp", (DL_FUNC) &_PALM_fitModel_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PALM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
